public class AccountDAO implements IAccountDAO {
    
         public List<Sobject> createSobject(List<Sobject> sobjectList){
                Insert sobjectList;
                return sobjectList;
        }
    
         public List<Sobject> updateSobject(List<Sobject> sobjectList){
                update sobjectList;
                return sobjectList;
          }
    
         public List<Sobject> deleteSobject(List<Sobject> sobjectList){
                delete sobjectList;
                return sobjectList;
          }
}